model_path: "./models/llama/"
data_path: "./data/PUD/"
vacancies_path: "./data/Вакансии_обработанные_фильтр_5000/"
output_folder: "./results/"
sbert_model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
# SBERT заточенный под русский язык: "ai-forever/ru-en-RoSBERTa"
# Популярная модель SBERT "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

top_faculties: 3  # Количество топовых факультетов
top_disciplines_per_faculty: 5  # Количество топовых дисциплин для каждого факультета
top_disciplines: 25  # Количество топовых дисциплин в режиме дисциплин
analysis_mode: "discipline_only"  # Можно установить "faculty_based" или "discipline_only"

# Параметры обработки строк
processing:
  mode: 'random'  # Опции: 'all', 'range', 'solo', 'random'
  start_index: 0  # Используется, если mode = 'range'
  end_index: 2    # Используется, если mode = 'range'
  solo_index: 0   # Используется, если mode = 'solo'
  random_count: 2   # Используется, если mode = 'random'

# Параметры генерации ключевых слов
generation_params:
  max_new_tokens: 200
  num_return_sequences: 1
  do_sample: True
  top_k: 15
  top_p: 0.9
